name: "Some new copilot metrics action"
description: "This is forwarding to real action"

inputs:
  license-key:
    required: true
    description: "PAT token that gives access to private repo"
  auhtorization-token:
    required: true
    description: "PAT token to authenticate to the GitHub API so we can extract values"
    

runs:
  using: "composite"
  steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Checkout private action
      uses: actions/checkout@v4
      with:
        repository: Falck-Studios/github-copilot-metrics
        token: ${{ inputs.license-key }}
    - name: List dir
      run: ls .
    - name: List next dir
      run: ls ./github-copilot-metrics
    - name: "Fetch Copilot Metrics using secret action"
      uses: ./github-copilot-metrics
      with:
        token: ${{ inputs.authorization-token }}
        org: ${{ github.repository_owner }}
        file-name: copilot-metrics
